import type { Metadata } from "next";
import { Inter, Space_Grotesk, Readex_Pro, Fira_Sans } from "next/font/google";
import "../styles/globals.scss";
import "../styles/var.module.scss";

const inter = Inter({ subsets: ["latin"] });

const firaSans = Fira_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-firaSans",
});

const spaceGrotesk = Space_Grotesk({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-spaceGrotesk",
});

const readexPro = Readex_Pro({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-readexPro",
});

export const metadata: Metadata = {
  title: "PixelCraft - Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt"
      className={`${firaSans.variable} ${spaceGrotesk.variable} ${readexPro.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
